# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Fill My Basket' do

  use_frameworks!

  pod “TextFieldEffects”

  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  pod 'Firebase/Core'
  pod 'Firebase/Auth’
  pod ‘GoogleSignIn’

end
